feat: add scripts to uninstall packages

diff --git a/scripts/alias-package b/scripts/alias-package
--- a/scripts/alias-package
+++ b/scripts/alias-package
@@ -2,18 +2,54 @@
 
 set -euo pipefail
 
-package=${1}
-version=${2}
-version_alias=${3}
+cmd=$(basename "${0}")
+package=${1:-}
+version=${2:-}
+version_alias=${3:-}
 
-bin_install_root="${HOME}/.bin"
-bin_install_target="${bin_install_root}/${package}/${version}"
-bin_install_alias="${bin_install_root}/${package}/${version_alias}"
-
-if [ ! -d "${bin_install_target}" ]; then
-  echo "✘ cannot alias to non-existent package version (${bin_install_target})" >&2
+if [ -z "${package}" ]; then
+  echo "✘ missing package" >&2
   exit 1
 fi
 
-ln -nfs "${bin_install_target}" "${bin_install_alias}"
-echo "✓ aliased ${package} '${version_alias}' → '${version}'"
+if [ -z "${version}" ]; then
+  echo "✘ missing version" >&2
+  exit 1
+fi
+
+bin_install_root="${HOME}/.bin"
+
+if [ "${cmd}" = "alias-package" ]; then
+  bin_install_target="${bin_install_root}/${package}/${version}"
+  bin_install_alias="${bin_install_root}/${package}/${version_alias}"
+
+  if [ -z "${version_alias}" ]; then
+    echo "✘ missing version alias" >&2
+    exit 1
+  fi
+
+  if [ ! -d "${bin_install_target}" ]; then
+    echo "✘ cannot alias to non-existent package version (${bin_install_target})" >&2
+    exit 1
+  fi
+
+  ln -nfs "${bin_install_target}" "${bin_install_alias}"
+  echo "✓ aliased ${package} '${version_alias}' → '${version}'"
+elif [ "${cmd}" = "unalias-package" ]; then
+  bin_install_alias="${bin_install_root}/${package}/${version}"
+
+  if [ -L "${bin_install_alias}" ]; then
+    local former_target=$(readlink "${bin_install_alias}")
+    rm "${bin_install_alias}"
+    echo "✓ unaliased ${package} '${version}' (was '${former_target}')"
+  elif [ -e "${bin_install_alias}" ]; then
+    echo "✘ cannot remove non-alias (${bin_install_alias})" >&2
+    exit 1
+  else
+    echo "✓ alias not found, nothing to do (${bin_install_alias})" >&2
+    exit 1
+  fi
+else
+  echo "✘ unknown command name: ${cmd}" >&2
+  exit 1
+fi
diff --git a/scripts/install-node b/scripts/install-node
--- a/scripts/install-node
+++ b/scripts/install-node
@@ -2,6 +2,8 @@
 
 set -euo pipefail
 
+cmd=$(basename ${0})
+
 version=
 set_lts=false
 architecture=
@@ -9,9 +11,9 @@ architecture=
 while [ $# -gt 0 ]; do
   case "${1}" in
     -h|--help)
-      echo "usage: install-node [--lts] <version>"
+      echo "usage: ${cmd} [--lts] <version>"
       echo
-      echo "Installs Node.js with the specified <version> and optionally aliases"
+      echo "Manages Node.js installs with the specified <version> and optionally aliases"
       echo "it to 'lts' given the '--lts' flag."
       exit 0
       ;;
@@ -48,22 +50,39 @@ else
   architecture="linux-x64"
 fi
 
-tarball_url="https://nodejs.org/dist/v${version}/node-v${version}-${architecture}.tar.gz"
-
 scripts_directory="${0:a:h}"
-"${scripts_directory}/install-package" \
-  node \
-  "${version}" \
-  "${tarball_url}"
 
-if [ "$("${HOME}/.bin/node/${version}/bin/node" -v 2>/dev/null)" != "v${version}" ]; then
-  echo "✘ verification of node ${version} failed" >&2
-  exit 1
-fi
+if [ "${cmd}" = "install-node" ]; then
+  tarball_url="https://nodejs.org/dist/v${version}/node-v${version}-${architecture}.tar.gz"
 
-if [ "${set_lts}" = "true" ]; then
-  "${scripts_directory}/alias-package" \
+  "${scripts_directory}/install-package" \
     node \
     "${version}" \
-    lts
+    "${tarball_url}"
+
+  if [ "$("${HOME}/.bin/node/${version}/bin/node" -v 2>/dev/null)" != "v${version}" ]; then
+    echo "✘ verification of node ${version} failed" >&2
+    exit 1
+  fi
+
+  if [ "${set_lts}" = "true" ]; then
+    "${scripts_directory}/alias-package" \
+      node \
+      "${version}" \
+      lts
+  fi
+elif [ "${cmd}" = "uninstall-node" ]; then
+  "${scripts_directory}/uninstall-package" \
+    node \
+    "${version}"
+  
+  if [ "${set_lts}" = "true" ]; then
+    "${scripts_directory}/unalias-package" \
+      node \
+      "${version}" \
+      lts
+  fi
+else
+  echo "✘ unknown command name: ${cmd}" >&2
+  exit 1
 fi
diff --git a/scripts/install-package b/scripts/install-package
--- a/scripts/install-package
+++ b/scripts/install-package
@@ -2,23 +2,51 @@
 
 set -euo pipefail
 
-package=${1}
-version=${2}
-tarball_url=${3}
+cmd=$(basename "${0}")
+package=${1:-}
+version=${2:-}
+tarball_url=${3:-}
+
+if [ -z "${package}" ]; then
+  echo "✘ missing package" >&2
+  exit 1
+fi
+
+if [ -z "${version}" ]; then
+  echo "✘ missing version" >&2
+  exit 1
+fi
 
 bin_install_root="${HOME}/.bin"
 bin_install_target="${bin_install_root}/${package}/${version}"
 
-if [ -d "${bin_install_target}" ]; then
-  echo "✓ ${package} ${version} already installed at ${bin_install_target}"
+if [ "${cmd}" = "install-package" ]; then
+  if [ -z "${tarball_url}" ]; then
+    echo "✘ missing url" >&2
+    exit 1
+  fi
+
+  if [ -d "${bin_install_target}" ]; then
+    echo "✓ ${package} ${version} already installed at ${bin_install_target}"
+  else
+    echo "📦 installing ${package} ${version} at ${bin_install_target}"
+    mkdir -p "${bin_install_target}"
+    curl \
+      --silent \
+      --location \
+      --output - \
+      "${tarball_url}" \
+    | tar xz --strip-components 1 -C "${bin_install_target}"
+    echo "✓ ${package} ${version} installed at ${bin_install_target}"
+  fi
+elif [ "${cmd}" = "uninstall-package" ]; then
+  if [ -d "${bin_install_target}" ]; then
+    rm -rf "${bin_install_target}"
+    echo "✓ ${package} ${version} uninstalled from ${bin_install_target}"
+  else
+    echo "✓ ${package} ${version} was not found at ${bin_install_target}, nothing to do"
+  fi
 else
-  echo "📦 installing ${package} ${version} at ${bin_install_target}"
-  mkdir -p "${bin_install_target}"
-  curl \
-    --silent \
-    --location \
-    --output - \
-    "${tarball_url}" \
-  | tar xz --strip-components 1 -C "${bin_install_target}"
-  echo "✓ ${package} ${version} installed at ${bin_install_target}"
+  echo "✘ unknown command name: ${cmd}" >&2
+  exit 1
 fi
